services:
  springboot-service:
    image: rushikeshdoc/backend:githubactionb
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/hrmsportal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql-service
    networks:
      - mynetwork
       
  frontend:
    image: rushikeshdoc/frontend:hrmstej04
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - mysql-service
    networks:
      - mynetwork
     
  mysql-service:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hrmsportal"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
        
networks:
  mynetwork:

volumes:
  mysql-data:

